# Introduction {#introduction}

The goal of model selection is to identify the _best_ model among a set of competing models. What exactly means the best model? Usually, we consider the best model to be the _simplest_ of the _best fitting_ models, however, it is not exactly clear what the _simplest_ or the _best fitting_ model means. Consider for instance the following example:

```{r 01-intro-model, echo = FALSE, fig.show = 'hold', fig.cap='Example problem: which model is the best model?', out.width='50%', fig.asp=.75, fig.align='left'}
plot.model <- function(df, model, title, idx){
  SSE <- round(sum(model[[idx]]$residuals ^ 2), 0)
  k <- length(model[[idx]]$coefficients)
  p <- ggplot2::ggplot(df, aes(x,y)) +
    geom_point() +
    theme_book() +
    ggtitle(title[idx]) +
    geom_smooth(formula = formula(model[[idx]]), method = 'lm', se = FALSE) +
    annotate('text', x = 4, y = 700,
              label = paste('   SSE =', SSE, '\nk =', k),
              size = 7)
}

# generate data
set.seed(123)
df <- tibble::tibble(x = seq(20), y = jitter(2 * x ^ 2, amount = 60))
# fit different models
model <- vector(mode="list", length=3)
model[[1]] <-lm(y ~ x, df)
model[[2]] <- lm(y ~ x + I(x ^ 2), df)
model[[3]] <- lm(y ~ poly(x, 15), df)

title <- c('Linear model', 'Quadratic model', 'Polynomial of degree 15')

plots <- purrr::map(
  seq(3),
  .f = function(.) plot.model(df, model, title, .)
  )

# do not show console output, only plots
invisible(lapply(plots, function(x) show(x)))
```

Here, $k$ corresponds to the number of parameters (including the intercept) and $SSE$ is the _sum of squared error_ given by $$SSE = \sum_{i = 1}^n (y_i - f(x_i))^2 ,$$
where $n$ corresponds to the number of observations (here $n = 20$), $y_i$ is the $i$th observation and $f(x_i)$ is the predicted reponse of model $f$ for observation $i$.

We observe that the $SSE$ significantly decreases with increasing $k$.
So which of the three models is the best model? When does a better fit justifies a more complex model?

To answer this question, we must decide on how to asses the quality of fit and how to measure model complexity.

How to measure quality of fit is the topic of the next chapter. Model complexity might be covered in another section.
